[Settings]
; Бу ерга дастурнинг уланиш манзилини (URL) киритинг.
; Агар онлайн бўлса: https://lifestore.uz
; Агар маҳаллий бўлса: http://lifestore.loc ёки http://localhost/lifestore
AppURL=http://lifestore
AppName=LifeStore POS
